services:
  app:
    build: .
    container_name: gestion-stagiaires-app
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: gestion_stagiaires
      DB_USERNAME: Bernard
      DB_PASSWORD: password
    depends_on:
      - db
    volumes:
      - .:/var/www
    working_dir: /var/www

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gestion_stagiaires
      MYSQL_USER: Bernard
      MYSQL_PASSWORD: password
    ports:
      - "33061:3306"
