version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      APP_ENV: production
      APP_DEBUG: false
      APP_URL: ${RAILWAY_STATIC_URL}
      DB_CONNECTION: mysql
      DB_HOST: mainline.proxy.rlwy.net
      DB_PORT: 26566
      DB_DATABASE: railway
      DB_USERNAME: root
      DB_PASSWORD: hWUKJASPVoFUQiOqbCHZchhNAjNSEyev
    command: php artisan serve --host=0.0.0.0 --port=8080
